defmodule Homework.Transactions.Transaction do
  use Ecto.Schema
  import Ecto.Changeset
  alias Homework.Merchants.Merchant
  alias Homework.Users.User
  alias Homework.Companies.Company
  alias Homework.Transactions.ConvertedAmount


  @primary_key {:id, :binary_id, autogenerate: true}
  schema "transactions" do
    # question: can amounts be negative if we have credit and debit fields?
    field(:amount, ConvertedAmount)
    # assuming that these are credit (amount increase) and debit (amount decrease), rather than using a credit or debit card for the transaction
    # question: is there a use case for having both debit and credit fields?
    # TODO possible changes for discussion:
    #   migrate credit and debit to be ConvertedAmount (scalar),
    #   merge fields into a single "transaction type" (enum?),
    #   remove credit and debit fields altogether and have positive values be credits and negative values debits
    field(:credit, :boolean, default: false)
    field(:debit, :boolean, default: false)
    field(:description, :string)

    belongs_to(:merchant, Merchant, type: :binary_id, foreign_key: :merchant_id)
    belongs_to(:user, User, type: :binary_id, foreign_key: :user_id)
    belongs_to(:company, Company, type: :binary_id, foreign_key: :company_id) # TODO this field should be autogenerated from the user company foreign key

    timestamps()
  end

  @doc false
  def changeset(transaction, attrs) do
    transaction
    |> cast(attrs, [:user_id, :amount, :debit, :credit, :description, :merchant_id, :company_id])
    |> validate_required([:user_id, :amount, :description, :merchant_id, :company_id])
  end
end
